export const PRODUCT_POST_REQ = "PRODUCT_POST_REQ";
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS";
export const PRODUCT_POST_FAILURE = "PRODUCT_POST_FAILURE";


export const USER_GET_REQ = "USER_GET_REQ";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";
