export const POST_ORDER_REQ = "POST_ORDER_REQ";
export const POST_ORDER_SUCCESS = "POST_ORDER_SCCESS";
export const POST_ORDER_FAILED = "POST_ORDER_FAILED";


export const GET_ORDER_REQ = "GET_ORDER_REQ";
export const GET_ORDER_SUCCESS = "GET_ORDER_SCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";
